language: cpp
sudo: require

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
    key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-8
      - clang-6.0

install:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7

matrix:
  include:
  - os: linux
    compiler: gcc
    before_script:
      - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
      - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
      - export CC=/usr/bin/gcc-7
      - export CXX=/usr/bin/g++-7

  - os: linux
    compiler: clang
    before_script:
      - sudo ln -s /usr/bin/clang-6.0 /usr/local/bin/clang
      - sudo ln -s /usr/bin/clang++-6.0 /usr/local/bin/clang++
      - export CC=/usr/bin/clang-6.0
      - export CXX=/usr/bin/clang++-6.0

script:
  - sudo pip install conan
  - mkdir build && cd build
  - cmake .. -DEML_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
  - make
  - if [ "${BUILD_ONLY}" != "1" ]; then ctest --verbose; fi
